"$schema" = 'https://starship.rs/config-schema.json'

[character] # The name of the module we are configuring is 'character'
format = ' $symbol '
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[➜](bold red)'
vimcmd_symbol = '[➜](bold blue)'
vimcmd_replace_one_symbol = '[➜](bold green)'
vimcmd_replace_symbol = '[➜](bold orange)'
vimcmd_visual_symbol = '[➜](bold purple)'

[git_status]
style = 'bold purple'
ahead = '↑'
behind = '↓'
diverged = '⥯'

